#!/usr/bin/env bash

# Make wine use system language.
if [[ -n "$LC_ALL" ]]; then
    lang="$LC_ALL"
elif [[ -n "$LANG" ]]; then
    lang="$LANG"
else
    lang=C
fi
"$WINELOADER" reg add "HKCU\\Environment" /v LC_ALL /t REG_SZ /d "$lang" /f

if [[ -z "$SNAP" ]]; then
    LOGOS_VERSION=$(curl -s "https://clientservices.logos.com/update/v1/feed/logos10/stable.xml" \
        | xmlstarlet select -N a="http://www.w3.org/2005/Atom" \
            -t -m "//a:feed/a:entry" -v "logos:version" -n \
        | sort -rn \
        | head -n1)
    export LOGOS_VERSION
    export INSTALL_URL="https://downloads.logoscdn.com/LBS10/Installer/${LOGOS_VERSION}/Logos-x64.msi"
fi

# Use installer in Downloads folder if correct version.
dl_dir=$(xdg-user-dir DOWNLOAD)
if [[ -e "${dl_dir}/Logos-x64.msi" ]]; then
    # Check installer version.
    ver_msi="$(file "${dl_dir}/Logos-x64.msi" | sed -r 's/.* Revision Number: .*\}([0-9\.]+);.*/\1/')"
    # URL version =~ 25.2.0.0052, but MSI version =~ 25.2.52, so:
    #   - ignore 3rd field '.0'
    #   - strip leading 0s in 4th field
    v_major="$(echo "$LOGOS_VERSION" | awk -F'.' '{print $1}')"
    v_minor="$(echo "$LOGOS_VERSION" | awk -F'.' '{print $2}')"
    # v_extra="$(echo "$LOGOS_VERSION" | awk -F'.' '{print $3}')" # unused field?
    v_patch="$(echo "$LOGOS_VERSION" | awk -F'.' '{print $4}' | sed -r 's/^0*//')" # remove leading 0s
    ver_url_compact="${v_major}.${v_minor}.${v_patch}"
    if [[ "$ver_msi" == "$ver_url_compact" ]]; then
        echo "${dl_dir}/Logos-x64.msi version ($ver_msi) matches URL version ($LOGOS_VERSION)."
        echo "Installing from downloaded installer."
        # Unset INSTALL_URL from snapcraft.yaml.
        export INSTALL_URL=
        # Set INSTALL_EXE.
        export INSTALL_EXE="${dl_dir}/Logos-x64.msi"
    else
        echo "${dl_dir}/Logos-x64.msi version ($ver_msi) does not match URL version ($LOGOS_VERSION)."
        echo "Downloading installer from URL."
    fi
fi
