#!/usr/bin/env bash

# Get latest Logos 10 version and installer link on-the-fly.
curl -s "https://clientservices.logos.com/update/v1/feed/logos10/stable.xml" \
    | xmlstarlet select -N a="http://www.w3.org/2005/Atom" \
    -t -m "//a:feed/a:entry" -v "logos:version" -n | sort -rn | head -n1

# xml_file="${HOME}/logos10-releases.xml"
# if [[ -f "$xml_file" ]]; then
#     read -p "Download latest $(basename $xml_file) file? [y/N]" ans
# fi

# if [[ ! -f "$xml_file" || "${ans,,}" == 'y' ]]; then
#     curl -s "https://clientservices.logos.com/update/v1/feed/logos10/stable.xml" > "$xml_file"
# fi

# xmlstarlet select -N a="http://www.w3.org/2005/Atom" \
#     -t -m "//a:feed/a:entry" -v "logos:version" -n "$xml_file" | sort -rn | head -n1
