#!/usr/bin/env bash

logos_exe="$(find "$SNAP_USER_COMMON" -name Logos.exe | grep Logos/Logos.exe)"
logos_dir="$(dirname "$logos_exe")"
if [[ "${1}" == 'all' ]]; then
	rm -fv "${logos_dir}"/Data/*/BibleIndex/*
	rm -fv "${logos_dir}"/Data/*/LibraryIndex/*
	rm -fv "${logos_dir}"/Data/*/PersonalBookIndex/*
	rm -fv "${logos_dir}"/Data/*/LibraryCatalog/*
elif [[ "${1}" == 'library' ]]; then
	rm -fv "${logos_dir}"/Data/*/LibraryCatalog/*
fi
