name: logos10-unofficial
title: Logos Bible Study App v10 (via WINE)
# core20 ideas from https://github.com/mmtrt/notepad-plus-plus
base: core20
adopt-info: version
# version: "25.2.0.0056" # matches installer version below
# grade: devel # stable
summary: An invaluable tool for anyone who wants to go deeper in their studies.
description: |
  NOTE: Due to the way this app manages multiple windows it is incompatible with snap confinement policy.
  Until a solution is found the snap needs to be installed with the '--devmode' flag to work properly. So,
  for the beta release:
  
  `sudo snap install logos10-unofficial --devmode --beta`

  The Logos Bible Study app contains a powerful Bible study and sermon prep platform that allows you to study Scripture and consult commentaries, devotionals, Bible dictionaries, and more—all from your computer, tablet, or phone.
confinement: strict # devmode
license: GPL-3.0
website: https://github.com/wasta-linux/logos10-snap
contact: nate_marti@sil.org
issues: https://github.com/wasta-linux/logos10-snap/issues
icon: snap/gui/logos10-unofficial.png
architectures:
  - amd64

environment:
  # SOMMELIER_NO_THEME: "true" # avoid crash b/c of Light theme
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc
  TRICKS: "corefonts tahoma fontsmooth=rgb d3dcompiler_47 win10"
  WINEDLLOVERRIDES: "mscoree=;mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko

apps:
  logos10-unofficial:
    extensions: [gnome-3-38]
    command: bin/sommelier run-exe
    environment:
      INSTALL_URL: "https://downloads.logoscdn.com/LBS10/Installer/${SNAP_VERSION}/Logos-x64.msi"
      INSTALL_FLAGS: "/passive"
      RUN_EXE: "C:/users/${USER}/AppData/Local/Logos/System/Logos.exe"

  init:
    extensions: [gnome-3-38]
    command: bin/sommelier
    environment:
      INIT: '1'

  indexer:
    extensions: [gnome-3-38]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "C:/users/${USER}/AppData/Local/Logos/System/LogosIndexer.exe"

  kill-logos:
    extensions: [gnome-3-38]
    command: bin/kill-main-app

  kill-procs:
    extensions: [gnome-3-38]
    command: bin/kill-procs

  list-procs:
    extensions: [gnome-3-38]
    command: bin/list-procs
  
  watch-procs:
    extensions: [gnome-3-38]
    command: bin/watch-procs

  remove-all-indexes:
    extensions: [gnome-3-38]
    command: bin/remove-indexes all

  remove-library-index:
    extensions: [gnome-3-38]
    command: bin/remove-indexes LibraryIndex

  remove-wine-prefix:
    extensions: [gnome-3-38]
    command: bin/sommelier winetricks annihilate

  regedit:
    extensions: [gnome-3-38]
    command: bin/sommelier regedit

  wine:
    extensions: [gnome-3-38]
    command: bin/sommelier

  winecfg:
    extensions: [gnome-3-38]
    command: bin/sommelier winecfg

  winetricks:
    extensions: [gnome-3-38]
    command: bin/sommelier winetricks

plugs:
  # something that allows "ptrace" is needed for confinement to work; use --devmode as a workaround
  audio-playback:
  desktop:
  desktop-legacy:
  home:
  network:
  removable-media:
  wayland:
  x11:

  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-staging:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-staging-core20

parts:
  version:
    build-packages:
      - curl
      - xmlstarlet
    plugin: nil
    override-build: |
      ver=$(curl -s "https://clientservices.logos.com/update/v1/feed/logos10/stable.xml" \
        | xmlstarlet select -N a="http://www.w3.org/2005/Atom" \
          -t -m "//a:feed/a:entry" -v "logos:version" -n \
        | sort -rn \
        | head -n1)
      snapcraftctl set-version "$ver"
      snapcraftctl set-grade "devel" # stable

  data:
    plugin: dump
    source: data/
    organize:
      "*": data/
    stage:
      - data

  debs:
    plugin: nil
    stage-packages:
      - file
      - libmagic1
      - libmagic-mgc
      - procps
    prime:
      - bin/kill
      - usr/bin/file
      - usr/bin/pgrep
      - usr/bin/pkill
      - usr/bin/watch
      - usr/lib/file/magic.mgc
      - usr/lib/x86_64-linux-gnu/libmagic.so.1*

  # This reverts changes from https://github.com/snapcore/snapcraft/pull/3586
  fix-fontconfig:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i '/snap-package/,+1d' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  # Ref: https://github.com/mmtrt/notepad-plus-plus
  fix-bindtext:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -2 | head -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  hooks:
    plugin: dump
    source: hooks/
    organize:
      "*": sommelier/hooks/
    stage:
      - sommelier

  scripts:
    plugin: dump
    source: scripts/
    organize:
      "*": bin/
    stage:
      - bin

  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"
    override-prime: |
      snapcraftctl prime # core20

      # Don't let yad dialogs stay always-on-top.
      sed -r -i 's|(yad.*) --on-top|\1|g' bin/sommelier
      # # Remove annoying yad dialog for interactive MSI install.
      # sed -r -i 's|(yes.*Installing .*EXE_NAME.*)|# \1|' bin/sommelier
      # sed -r -i 's|(.*INSTALL_YAD_PID)|# \1|g' bin/sommelier

      # Add init-only command.
      sed -r -i 's|(\s+)(init_wine)$|\1\2\n\1if [[ $INIT == '1' ]]; then exit 0; fi|' bin/sommelier
